const DayActionTypes = {
  FETCH_LOCATION_START: 'FETCH_LOCATION_START',
  FETCH_LOCATION_SUCCESS: 'FETCH_LOCATION_SUCCESS',
  FETCH_LOCATION_FAILURE: 'FETCH_LOCATION_FAILURE',
  FETCH_WEATHER_START: 'FETCH_WEATHER_START',
  FETCH_WEATHER_SUCCESS: 'FETCH_WEATHER_SUCCESS',
  FETCH_WEATHER_FAILURE: 'FETCH_WEATHER_FAILURE'
};

export default DayActionTypes;
